version: "3.8"

networks:
  backend:
    driver: bridge

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-application
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./api
        target: /code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file: .env
    restart: always
    networks:
      - backend

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: django-application
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: ./app
        target: /code
    env_file: .env
    restart: always
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - 5432:5432
    restart: always
    env_file: .env
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - 5050:80
    env_file: .env
    restart: always
    networks:
      - backend