# Generated by Django 3.2.13 on 2024-05-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('measurements_id', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('shoulder_width', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('hip', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('inseam', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('outseam', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rise', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('flaws', models.TextField(blank=True)),
                ('brand', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.TextField(choices=[(None, 'Wybierz stan'), ('decent', 'Zadowalający'), ('good', 'Dobry'), ('very_good', 'Bardzo dobry'), ('new', 'Nowy bez metek'), ('new_with_tags', 'Nowy z metkami')], default=None)),
                ('category', models.TextField(choices=[(None, 'Wybierz kategorię'), ('bottom_garment', 'Bottom Garment'), ('top_garment', 'Top Garment'), ('accessories', 'Accessories')], default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurements_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.measurements')),
            ],
        ),
    ]
