# Generated by Django 5.0.6 on 2024-05-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Measurements',
            new_name='Measurement',
        ),
    ]
