# Generated by Django 5.0.6 on 2024-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_rename_brands_brand_rename_measurements_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[(None, 'Not selected'), ('bottom_garment', 'Bottom Garment'), ('top_garment', 'Top Garment'), ('accessories', 'Accessories')], default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[(None, 'Not selected'), ('decent', 'Decent'), ('good', 'Good'), ('very_good', 'Very good'), ('new_without_tags', 'New without tags'), ('new_with_tags', 'New with tags')], default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='flaws',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[(None, 'Size'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(),
        ),
    ]
