# Generated by Django 5.0.6 on 2024-06-20 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_listing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_photos/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
