# Generated by Django 5.0.6 on 2024-06-24 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('bought_for', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('sold_for', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.listing')),
            ],
        ),
    ]
