# Generated by Django 5.0.6 on 2024-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bought_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sold_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
