# Generated by Django 5.0.6 on 2024-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[(None, 'Not selected'), ('decent', 'Decent'), ('good', 'Good'), ('very_good', 'Very good'), ('new_without_tags', 'New without tags'), ('new_with_tags', 'New with tags')], default=None, null=True),
        ),
    ]
