# Generated by Django 5.0.6 on 2024-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_alter_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Not selected'), ('bottom_garment', 'Bottom Garment'), ('top_garment', 'Top Garment'), ('accessories', 'Accessories')], default=None, null=True),
        ),
    ]
