# Generated by Django 5.0.6 on 2024-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_alter_listing_measurements_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
